name: Continuous Integration

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  frontend:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend
      
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version-file: .nvmrc
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json
    - name: Upgrade npm version
      # Using npm 7 until I can fix some version inconsistencies.
      # Things generally seem to work right now but npm 8 is stricter and (correctly) points out some issues.
      #
      # Also, upgrading npm after setup-node is non-ideal because the latter actually uses npm (for the caching part).
      # But I don't know a better option right now.
      run: npm install -g npm@7
    - run: npm --version
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
